import architecture from "@/content/architecture.md?raw";
import appCreation from "@/content/app-creation.md?raw";
import broadCore from "@/content/broad-core.md?raw";
import broadExtensions from "@/content/broad-extensions.md?raw";
import broadMonetization from "@/content/broad-monetization.md?raw";
import broadUIFlows from "@/content/broad-ui-flows.md?raw";
import uiFlowsOnboarding from "@/content/ui-flows-onboarding.md?raw";
import uiFlowsPaywall from "@/content/ui-flows-paywall.md?raw";
import uiFlowsSettingsSupport from "@/content/ui-flows-settings-support.md?raw";
import compatibility from "@/content/compatibility.md?raw";
import documentation from "@/content/documentation.md?raw";
import gettingStarted from "@/content/getting-started.md?raw";
import glossary from "@/content/glossary.md?raw";
import legacyBroadCore from "@/content/legacy-broadcore.md?raw";
import legacyAppMigration from "@/content/legacy-app-migration.md?raw";
import migration from "@/content/migration.md?raw";
import moduleSelection from "@/content/module-selection.md?raw";
import publicPackageAccess from "@/content/public-package-access.md?raw";
import releaseProcess from "@/content/release-process.md?raw";
import specialOffer from "@/content/special-offer.md?raw";
import adaptySetup from "@/content/adapty-setup.md?raw";
import adaptyIntegrationGuide from "@/content/adapty-integration-guide.md?raw";
import onboardingATT from "@/content/onboarding-att.md?raw";
import paywallUI from "@/content/paywall-ui.md?raw";
import ruBilling from "@/content/ru-billing.md?raw";
import ruSpecialOffer from "@/content/ru-special-offer.md?raw";
import ruBillingAccountManager from "@/content/ru-billing-account-manager.md?raw";
import ruBillingABTestsDeveloper from "@/content/ru-billing-ab-tests-developer.md?raw";
import ruBillingABPlatform from "@/content/ru-billing-ab-platform.md?raw";
import backendProductCatalog from "@/content/backend-product-catalog.md?raw";
import runtimeReliability from "@/content/runtime-reliability.md?raw";
import tokenPaywall from "@/content/token-paywall.md?raw";
import usedesk from "@/content/usedesk.md?raw";

export type DocEntry = {
  slug: string;
  title: string;
  description: string;
  purpose: string;
  when: string;
  outcome: string;
  group: "Старт" | "Части платформы" | "BroadUIFlows" | "Монетизация" | "Архитектура" | "Разработка";
  body: string;
};

export const docs: DocEntry[] = [
  { slug: "getting-started", title: "Первое подключение", description: "Работающий BroadStart: реальные скриншоты Xcode, подключение библиотек и первый запуск на iPhone Simulator.", purpose: "Подключить готовый общий код без лишних и продублированных зависимостей.", when: "Когда добавляете BroadApps в новый или существующий Xcode-проект.", outcome: "Выбранные библиотеки загружены, приложение собирается и нужные функции открываются.", group: "Старт", body: gettingStarted },
  { slug: "app-creation", title: "Создание приложения", description: "От требований до работающего сценария: разбор BroadStart, код, состояния, работа вручную и с агентом.", purpose: "Провести новое приложение от исходных требований до передачи в QA.", when: "До первого изменения Swift-кода нового приложения.", outcome: "Есть подтверждённый план, один рабочий сценарий и список оставшихся проверок.", group: "Старт", body: appCreation },
  { slug: "module-selection", title: "Какие части платформы выбрать", description: "Четыре модуля, пять практических наборов и точное различие между пакетом, product и target.", purpose: "Подключить все нужные возможности без лишних и продублированных зависимостей.", when: "До добавления библиотек в Xcode.", outcome: "Для каждой функции выбран модуль, а каждому прямому import соответствует product в target.", group: "Старт", body: moduleSelection },
  { slug: "public-package-access", title: "Подключение без пароля", description: "Публичные адреса, проверка без аккаунта и диагностика ошибок Xcode, кеша и ревизий.", purpose: "Скачать открытые библиотеки платформы без аккаунта и секретного токена.", when: "Когда Xcode просит войти в GitHub или не может скачать библиотеку.", outcome: "В проекте стоят открытые адреса GitHub, и Xcode скачивает код без авторизации.", group: "Старт", body: publicPackageAccess },
  { slug: "legacy-broadcore", title: "Старый BroadCore: куда переехал", description: "Где теперь находятся функции старой платформы и как отличить имя BroadCore от адреса его репозитория.", purpose: "Не принять архивный BroadCore за актуальную платформу.", when: "Когда ссылка или поиск привели в BroadApps-official/BroadCore.", outcome: "Вы открыли актуальный модуль или инструкцию миграции.", group: "Старт", body: legacyBroadCore },
  { slug: "legacy-app-migration", title: "Переход со старого BroadCore", description: "Аудит зависимостей, сохранение правок приложения, переключение групп и проверка прежнего поведения.", purpose: "Обновить существующее приложение без большого переписывания.", when: "Когда в проекте есть старый BroadCore, библиотека из папки на Mac или скопированные файлы платформы.", outcome: "Старое подключение удалено только после проверки каждой затронутой функции приложения.", group: "Старт", body: legacyAppMigration },
  { slug: "glossary", title: "Словарь без жаргона", description: "Термины Xcode, Swift, данных, оплаты и выпуска: понятные определения, примеры и ссылки на инструкции.", purpose: "Быстро расшифровать незнакомое слово из инструкции.", when: "Когда термин мешает понять действие или ожидаемый результат.", outcome: "Вы понимаете слово и сразу возвращаетесь к конкретному шагу инструкции.", group: "Старт", body: glossary },
  { slug: "broad-core", title: "BroadCore", description: "Основа запуска приложения: последовательность старта, кеш, повтор запросов и безопасные логи.", purpose: "Дать приложению общие механизмы запуска и восстановления после ошибок.", when: "Когда нужен запуск, кеш, логи, повтор запроса или ATT.", outcome: "Приложение запускает критические шаги по порядку и понятно сообщает об ошибках.", group: "Части платформы", body: broadCore },
  { slug: "broad-extensions", title: "BroadExtensions", description: "Маленькие готовые функции для цвета, клавиатуры и навигации — без оплаты и остальных частей платформы.", purpose: "Повторно использовать небольшие Swift-функции без подключения всей платформы.", when: "Когда нужны только маленькие функции языка или интерфейса.", outcome: "Приложение получает утилиты, но не загружает Core, Adapty или готовые экраны.", group: "Части платформы", body: broadExtensions },
  { slug: "broad-monetization", title: "BroadMonetization", description: "Общая логика покупки и восстановления для приложения, которое рисует экран оплаты самостоятельно.", purpose: "Использовать готовую платёжную логику со своим дизайном экранов.", when: "Когда приложение рисует экран оплаты само, но не хочет заново писать работу с покупками.", outcome: "Экран получает все варианты покупки и открывает Premium только после подтверждения.", group: "Части платформы", body: broadMonetization },
  { slug: "broad-ui-flows", title: "BroadUIFlows", description: "Готовые экраны первого запуска, подписки и переходов внутри приложения.", purpose: "Быстро добавить готовые пользовательские экраны поверх платёжной логики.", when: "Когда приложению нужен готовый интерфейс, а не только методы покупки.", outcome: "Приложение передаёт свои тексты и настройки, а библиотека показывает нужные экраны.", group: "Части платформы", body: broadUIFlows },
  { slug: "ui-flows-onboarding", title: "Онбординг: шесть полных проходов", description: "Все слайды, появление paywall, закрытие оффера и выход на главную в шести приложениях.", purpose: "Сравнить полные маршруты первого запуска и настроить свой.", when: "Когда создаёте, переносите или проверяете онбординг.", outcome: "Понятны последовательность шагов, переход к подписке и выход на главный экран.", group: "BroadUIFlows", body: uiFlowsOnboarding },
  { slug: "ui-flows-paywall", title: "BroadUIFlows: paywall и Special Offer", description: "Общий сценарий paywall и Special Offer; частные примеры 5007, 5092 и Claude232 с пояснением отличий.", purpose: "Увидеть полный переход во второе предложение и границу между UIFlows и Monetization.", when: "Когда проектируете или проверяете обычный paywall и Special Offer.", outcome: "Крестик открывает второй экран только по разрешённому сценарию, а Premium открывается только после подтверждения.", group: "BroadUIFlows", body: uiFlowsPaywall },
  { slug: "ui-flows-settings-support", title: "Экран настроек и экран поддержки", description: "Шесть приложений в видео: настройки, чат, письмо и понятный выход при недоступной почте.", purpose: "Выбрать оформление настроек и настроить понятный путь к чату или письму.", when: "Когда добавляете настройки и поддержку в приложение или проверяете готовую реализацию.", outcome: "Пользователь может открыть поддержку, вернуться и связаться с вами даже без настроенной почты.", group: "BroadUIFlows", body: uiFlowsSettingsSupport },
  { slug: "adapty-setup", title: "Adapty: что нужно передать", description: "Два значения для загрузки экрана оплаты: публичный ключ приложения и имя нужного экрана в Adapty.", purpose: "Подключить Adapty без дополнительных проверяющих сервисов и лишних настроек.", when: "Перед первой загрузкой экрана оплаты или при добавлении нового места показа.", outcome: "Ключ передан один раз, нужный экран назван явно, все варианты покупки сохранены.", group: "Монетизация", body: adaptySetup },
  { slug: "adapty-integration-guide", title: "Интеграция Adapty в iOS-приложении", description: "Полный путь от активации SDK и загрузки продуктов до регистрации показа, A/B-тестов, покупки и восстановления.", purpose: "Правильно встроить кастомный paywall Adapty и не потерять статистику показов и варианты эксперимента.", when: "Когда реализуете Adapty напрямую, проверяете кастомный paywall или разбираете пример приложения 5007.", outcome: "SDK активирован, placement загружает продукты, каждый реальный показ зарегистрирован, покупка и restore проверены.", group: "Монетизация", body: adaptyIntegrationGuide },
  { slug: "paywall-ui", title: "Экран подписки: четыре примера", description: "Четыре видео рядом: появление продуктов, переключение тарифов, крестик, спешл оффер и тестовая покупка.", purpose: "Сделать экран подписки понятным при любом ответе Adapty.", when: "Когда реализуете или проверяете экран подписки.", outcome: "Все варианты видны, загрузка не мигает, повторные нажатия заблокированы.", group: "Монетизация", body: paywallUI },
  { slug: "special-offer", title: "Спешл оффер (от Adapty)", description: "Как показать дополнительный экран Adapty после того, как пользователь закрыл первый paywall без покупки.", purpose: "Показать спешл оффер по флагу Adapty с окном показа и cooldown.", when: "Когда настраиваете предложение Adapty после закрытия первого экрана оплаты.", outcome: "special_offer = true открывает второй экран в окне показа; когда окно истекает, действует cooldown.", group: "Монетизация", body: specialOffer },
  { slug: "token-paywall", title: "Покупка токенов", description: "Как показать все пакеты, провести покупку один раз и обновить баланс только после ответа сервера.", purpose: "Продавать пакеты токенов и не потерять варианты, настроенные в Adapty.", when: "Когда приложение продаёт расходуемый баланс вместо подписки.", outcome: "Все пакеты показаны, покупка подтверждена сервером, баланс обновлён ровно один раз.", group: "Монетизация", body: tokenPaywall },
  { slug: "ru-billing", title: "RU Billing: карта и СБП", description: "Карта и СБП, серверные тарифы при недоступном Adapty, проверка региона и подтверждение оплаты.", purpose: "Безопасно добавить СБП и карту рядом с Apple без ложного Premium.", when: "Когда подключаете, проверяете или обновляете российские способы оплаты.", outcome: "Понятно, когда показать RU-способы, как провести checkout и чем подтверждается Premium.", group: "Монетизация", body: ruBilling },
  { slug: "ru-billing-account-manager", title: "RU Billing: менеджеру — спешл оффер", description: "Как отметить продукт Special Offer в каталоге backend и включить флаг показа в Remote Config. A/B-тесты пока в разработке.", purpose: "Подготовить продукт и разрешение показа без доступа к коду и без угадывания настроек.", when: "До передачи разработчику задачи на RU Billing Special Offer.", outcome: "Продукт помечен в каталоге backend, а разработчик получает Placement Id, id продукта и имя флага.", group: "Монетизация", body: ruBillingAccountManager },
  { slug: "ru-billing-ab-tests-developer", title: "RU Billing: A/B-тесты для разработчика", description: "Adapty выбирает вариант paywall, но RU-платёж проходит мимо StoreKit. Как связать показ варианта с оплатой и посчитать конверсию сегментов.", purpose: "Показать, как приложение отправляет назначение сегмента и показ paywall на backend, чтобы конверсия RU-оплаты считалась по вариантам Adapty.", when: "Когда в приложении с RU Billing нужно запустить A/B-тест paywall.", outcome: "Показ уходит ровно в один счётчик, сегмент и платёж склеиваются на backend по идентификатору пользователя.", group: "Монетизация", body: ruBillingABTestsDeveloper },
  { slug: "ru-billing-ab-platform", title: "RU Billing: A/B в платформе", description: "Подключение экспериментов без изменения работающей оплаты: общий tracker, выбор продуктов, настройка кодом и с агентом.", purpose: "Подключить opt-in эксперименты RU Billing через BroadMonetization.", when: "Когда RU Billing уже работает и нужны A/B-тесты.", outcome: "Один tracker, прежний checkout и проверенные настройки варианта.", group: "Монетизация", body: ruBillingABPlatform },
  { slug: "ru-special-offer", title: "RU Billing: Special Offer — RU-продукт", description: "Откуда берётся RU-продукт для Special Offer: платёжный каталог backend по отметке isSpecialOffer, а не Adapty или App Store.", purpose: "Выбрать RU-продукт для Special Offer из каталога backend без подмены.", when: "Когда общий Special Offer уже работает и нужно подставить RU-продукт.", outcome: "RU-продукт берётся из каталога по отметке и без подмены уходит в RU checkout.", group: "Монетизация", body: ruSpecialOffer },
  { slug: "backend-product-catalog", title: "RU Billing: продукты с backend", description: "Где настраивается запрос, как разобрать JSON и сохранить все RU-тарифы без потерь.", purpose: "Подключить backend конкретного приложения к общей платёжной логике через готовый или собственный decoder.", when: "Когда backend отдаёт продукты для СБП и карты.", outcome: "Каталог сохранён целиком: обычный RU paywall использует точное соответствие ID, а RU Special Offer выбирает продукт по isSpecialOffer.", group: "Монетизация", body: backendProductCatalog },
  { slug: "architecture", title: "Как устроена платформа", description: "Библиотеки, слои и ответственность на примере BroadStart: от нажатия до данных, оплаты и выбора места исправления.", purpose: "Понять, какой код принадлежит приложению, модулю и отдельному слою.", when: "Перед разработкой сценария или исправлением общей функции.", outcome: "У каждого действия есть владелец, а зависимости и настройки разделены.", group: "Архитектура", body: architecture },
  { slug: "onboarding-att", title: "Первые экраны и разрешение Apple", description: "Страницы, свой или готовый экран, два независимых отключения, условия ATT и переход к paywall и главной.", purpose: "Настроить первый запуск и системный запрос без повторов и неправильных переходов.", when: "Когда создаёте или меняете onboarding и ATT.", outcome: "Страницы завершаются по конфигурации, ATT появляется только при подходящих условиях.", group: "Архитектура", body: onboardingATT },
  { slug: "runtime-reliability", title: "Запуск, ошибки и восстановление", description: "Состояния BroadStart, ограниченный запуск, сохранение контента, двойной тап и восстановление незавершённой операции.", purpose: "Разделить загрузку, ошибку данных и неопределённый результат оплаты.", when: "Когда добавляете запуск, обновление экрана, кеш или восстановление.", outcome: "Пользователь видит результат и безопасное действие, а приложение не создаёт повторную операцию.", group: "Архитектура", body: runtimeReliability },
  { slug: "usedesk", title: "Чат поддержки Usedesk", description: "Что реально присылает менеджер и как из этих данных открыть готовый чат в приложении.", purpose: "Подключить Usedesk без придуманных требований, собственного экрана и лишней серверной архитектуры.", when: "Когда менеджер прислал Token, Company ID, Channel ID и web-script.", outcome: "Строка в настройках открывает готовый чат нужной компании и канала.", group: "Разработка", body: usedesk },
  { slug: "compatibility", title: "Какие версии ставить", description: "Проверенный набор, Exact Version и диапазоны, Package.resolved, обновление и возврат — вручную и с агентом.", purpose: "Подключить воспроизводимый набор библиотек и проверить фактические версии.", when: "При первом подключении, миграции и обновлении приложения.", outcome: "Ограничения и lockfile согласованы, затронутые сценарии проверены.", group: "Разработка", body: compatibility },
  { slug: "release-process", title: "Как выпускать новые версии", description: "От изменения и проверки кандидата до неизменяемого тега, общего набора и инструкции обновления приложения.", purpose: "Выпустить модуль с понятной совместимостью и доказанным результатом.", when: "Когда меняется общий код или готовится выпуск платформы.", outcome: "Кандидат и опубликованные версии проверены, разработчику понятны действия после обновления.", group: "Разработка", body: releaseProcess },
  { slug: "migration", title: "Почему платформу разделили", description: "Какие проблемы решило разделение, что осталось общим и как это влияет на новые и существующие приложения.", purpose: "Понять причины отдельных репозиториев и цену независимых выпусков.", when: "Когда нужно разобраться в старой и новой структуре платформы.", outcome: "Понятны роли четырёх модулей, integration repository и сайта.", group: "Разработка", body: migration },
  { slug: "documentation", title: "Как исправлять документацию", description: "Правка через GitHub или локально: источники API, понятные примеры, медиа, поиск, проверка и отдельная публикация.", purpose: "Сделать инструкцию применимой и согласовать её с проверенным кодом.", when: "Когда статья непонятна, устарела или меняется поведение платформы.", outcome: "Правка проверена, источники согласованы, состояние публикации известно.", group: "Разработка", body: documentation },
];

export const docGroups = ["Старт", "Части платформы", "BroadUIFlows", "Монетизация", "Архитектура", "Разработка"] as const;
export function getDoc(slug: string) { return docs.find((doc) => doc.slug === slug); }
export function slugifyHeading(value: string) {
  return value.toLocaleLowerCase("ru-RU").replace(/[`*_]/g, "").replace(/[^a-zа-яё0-9]+/gi, "-").replace(/^-|-$/g, "");
}
